config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :market_lists do
    resources :market_items, except: [:update, :edit, :index]
  end

  root to: 'market_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/market_item.rb
class MarketItem < ApplicationRecord
  belongs_to :market_list
  validates :name, presence: true, length: { minimum: 2, message: ' do item deve conter no mínimo 2 caracteres'}
  validates :quantidade, presence: true, numericality: { only_integer: true, greater_than: 0, message: ' deve ser maior que zero'}
end

app/models/market_list.rb
class MarketList < ApplicationRecord
    has_many :market_items, dependent: :destroy
    validates :name, presence: true, length: { minimum: 5, message: ' da lista deve conter no mínimo 5 caracteres' } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/market_items_controller.rb
class MarketItemsController < ApplicationController
  before_action :set_market_list, only: [:new, :create, :show, :destroy]
  before_action :set_market_item, only: [:show, :destroy]
 
  def new
    @market_item = MarketItem.new
  end
  
  def create
    @market_item = @market_list.market_items.new(market_item_params)
  
    if @market_item.save
      flash[:success] = "Item '#{@market_item.name}' criado com sucesso."
      redirect_to @market_list
    else
      flash[:danger] = market_item_errors
      render :new
    end
  end
  
  
  def destroy
    if @market_item.destroy
      flash[:success] = "Item '#{@market_item.name}' excluído com sucesso."
    else
      flash[:danger] = failed_destroy_message
    end
    
    redirect_to @market_item.market_list
  end

  def show
    # Já configurado no before_action set_market_item
  end

  private

  def failed_destroy_message
    "Erro ao excluir o item de mercado: #{market_item_errors}"
  end

  def set_market_list
    @market_list = MarketList.find(params[:market_list_id])
  end

  def set_market_item
    @market_item = @market_list.market_items.find(params[:id])
  end

  def market_item_params
    params.require(:market_item).permit(:name, :quantidade)
  end

  def market_item_errors
    @market_item.errors.full_messages.join(', ')
  end
end

app/controllers/market_lists_controller.rb
class MarketListsController < ApplicationController
  before_action :set_market_list, only: [:show, :edit, :update, :destroy]

  def index
    @market_lists = MarketList.order(market_date: :desc)
  end 
  
  def show
    # Já configurado no before_action set_market_list
  end  

  def create
    @market_list = MarketList.new(market_list_params)

    if @market_list.save
      flash[:success] = "Lista '#{@market_list.name}' criada com sucesso"
      redirect_to action: :index
    else
      set_flash_error
      render :new
    end
  end

  def update
    if @market_list.update(market_list_params)
      flash[:success] = "Lista '#{@market_list.name}' editada com sucesso"
      redirect_to @market_list
    else
      set_flash_error
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @market_list.destroy
      flash[:success] = "Lista '#{@market_list.name}' excluída com sucesso."
    else
      set_flash_error
    end
    redirect_to market_lists_path
  end

  def new
    @market_list = MarketList.new
  end

  def edit
    # Já configurado no before_action set_market_list
  end

  private

  def set_market_list
    @market_list = MarketList.find(params[:id])
  end

  def market_list_params
    params.require(:market_list).permit(:name, :market_date)
  end

  def set_flash_error
    flash[:danger] = @market_list.errors.full_messages.join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/market_items_helper.rb
module MarketItemsHelper
end

app/helpers/market_lists_helper.rb
module MarketListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SimpleMarketList</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>

<body>
  <div data-turbo-frame>
    <div class="notifications">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>

</html>

app/views/market_items/_form.html.erb
<%= form_for [@market_list, @market_item], html: { class: 'mb-4' } do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control col-md-6' %>
  </div>

  <div class="mb-3">
    <%= f.label :quantidade, class: 'form-label' %>
    <%= f.number_field :quantidade, class: 'form-control col-md-6' %>
  </div>

  <div class="mb-4">
    <%= f.submit 'Criar Item de Mercado', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/market_items/new.html.erb
<h1 class="mb-4">Novo Item de Mercado</h1>

<%= render 'form' %>

<%= link_to 'Voltar para a Lista de Mercado', @market_list, class: 'btn btn-primary' %>

app/views/market_items/show.html.erb
<h1 class="mb-4">Detalhes do Item de Mercado</h1>

<p class="mb-2"><strong>Nome:</strong> <%= @market_item.name %></p>
<p class="mb-4"><strong>Quantidade:</strong> <%= @market_item.quantidade %></p>

<%= link_to 'Voltar para a Lista de Mercado', market_list_path(@market_list), class: 'btn btn-primary' %>

app/views/market_lists/_form.html.erb
<div class="container">
  <%= form_for @market_list, html: { class: 'form mx-auto' } do |f| %>
    <div class="mb-3">
      <%= f.label :nome, class: 'form-label text-left' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= f.label :data, class: 'form-label text-left' %>
      <%= f.date_field :market_date, class: 'form-control' %>
    </div>

    <%= link_to 'Voltar para a Lista', market_lists_path, class: 'btn btn-primary mt-4' %> <%= f.submit 'Salvar', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/market_lists/edit.html.erb
<h2>Editar lista</h2>
<%= render 'form' %>

app/views/market_lists/index.html.erb
<h1 class="mb-4 mt-4 text-center">Lista de Compras</h1>

<ul class="list-group">
  <% @market_lists.each do |list| %>
    <li class="list-group-item d-flex justify-content-between align-items-center mb-2">
      <span>
        <%= "#{list.name}" %>
      </span>
      <div class="d-flex">
        <%= button_to edit_market_list_path(list), method: :get, class: 'btn btn-secondary', style: 'margin-right: 5px;' do %> 
          <i class="bi bi-pencil"></i>
        <% end %>
        <%= button_to list, method: :delete, data: { turbo_confirm: 'Tem certeza de que deseja excluir este item?' }, class: 'btn btn-danger', style: 'margin-right: 5px;' do %>
          <i class="bi bi-trash"></i> 
        <% end %>
        <%= button_to({ action: 'show', id: list.id }, method: :get, class: 'btn btn-secondary') do %>
          <i class="bi bi-eye"></i>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

<%= button_to 'Nova lista de Mercado', new_market_list_path, method: :get, class: 'btn btn-primary', style: 'margin-left: 10px;' %>

app/views/market_lists/new.html.erb
<div class="container mt-4">
  <h2 class="mb-4 text-center">Nova lista de mercado</h2>

  <%= render 'form' %>
</div>

app/views/market_lists/show.html.erb
<h1 class="mb-4"><%= @market_list.name %></h1>

<p><strong>Data de Criação:</strong> <%= @market_list.created_at.strftime("%d/%m/%Y") %></p>

<h2 class="mt-4">Itens da Lista:</h2>

<ul class="list-group">
  <% @market_list.market_items.each do |item| %>
    <li class="list-group-item d-flex justify-content-between align-items-center mb-2">
      <span><strong><%= item.quantidade %>x <%= item.name %></strong></span>
      <%= button_to market_list_market_item_path(@market_list, item), method: :delete, data: { turbo_confirm: 'Tem certeza de que deseja excluir este item?' }, class: 'btn btn-danger' do %>
        <i class="bi bi-trash"></i>
      <% end %>

    </li>
  <% end %>
</ul>

<%= link_to 'Voltar para a Lista', market_lists_path, class: 'btn btn-primary mt-4' %>
<%= link_to 'Novo Item de Mercado', new_market_list_market_item_path(@market_list), class: 'btn btn-primary mt-4' %>